# Install:
# `pre-commit install --install-hooks --overwrite`
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      name: black
      entry: black .
      language: python
      stages: [commit]
      always_run: true
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: python
      verbose: true
      pass_filenames: false
      always_run: true
      stages: [commit]
#    - id: mypy
#      name: mypy
#      entry: mypy dsvae
#      verbose: true
#      always_run: true
#      language: python
#      stages: [push]
#      pass_filenames: false
