wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
attention:
  desc: null
  value: false
batch_size:
  desc: null
  value: 128
beta:
  desc: null
  value: 0.2
bidirectional:
  desc: null
  value: false
channels:
  desc: null
  value: 9
dataset:
  desc: null
  value: gmd
debug:
  desc: null
  value: false
decoder:
  desc: null
  value: lstm
device:
  desc: null
  value: ''
disentangle:
  desc: null
  value: false
early_stop:
  desc: null
  value: 30
encoder:
  desc: null
  value: lstm
epochs:
  desc: null
  value: 200
file_shuffle:
  desc: null
  value: true
hidden_factor:
  desc: null
  value: 2
hidden_size:
  desc: null
  value: 512
input_shape:
  desc: null
  value:
  - 16
  - 27
input_size:
  desc: null
  value: 27
latent_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.0001
lstm_dropout:
  desc: null
  value: 0.2
max_anneal:
  desc: null
  value: 10
model_type:
  desc: null
  value: vae
n_layers:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 0
pattern_shuffle:
  desc: null
  value: false
scale_factor:
  desc: null
  value: 1
sequence_length:
  desc: null
  value: 16
task:
  desc: null
  value: groove
warm_latent:
  desc: null
  value: 50
