name: dsvae

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python
  - pytorch==1.7.0
  - pytest>=6.0
  - flake8
  - rope
  - onnx
  - pip

  - pip:
    - note_seq
    - onnxruntime
    - wandb
    - google-api-python-client
    - pre-commit
    - -e .
