# data
dataset: "gmd"
num_workers: 0
batch_size: 256  # input_tensor.shape[0]
input_size: 27  # input_tensor.shape[-1]
sequence_length: 16  # input_tensor.shape[1]
file_shuffle: True  # shuffles data loading across different MIDI patterns
pattern_shuffle: False  # shuffle sub-patterns within a MIDI pattern
scale_factor: 1
# model
model_type: "vae"
encoder: "lstm"
decoder: "lstm"
n_layers: 2
hidden_size: 512
latent_size: 8
bidirectional: False
attention: False
disentangle: False
lstm_dropout: 0.3
# optimization
beta: 10000
max_anneal: 200
warm_latent: 100
epochs: 250
lr: 0.0001
early_stop: 30
device: ""
